### Pass test ------------------------------------------------------------------

# type
expect_silent(check_class("chr", type = "character"))
expect_silent(check_class(2, type = "numeric"))
expect_silent(check_class(-1.4, type = "numeric"))
expect_silent(check_class(2L, type = "integer"))
expect_silent(check_class(TRUE, type = "logical"))
expect_silent(check_class(FALSE, type = "logical"))
expect_silent(check_class(NULL, type = "NULL"))
expect_silent(check_class(data.frame(A=c(1,2)), type = "data.frame"))

# allowNULL (Exception from e.g. character)
expect_silent(check_class(NULL, type = "character", allowNULL = TRUE))

### Errors ---------------------------------------------------------------------

# var
expect_error(check_class(type = "character"))

# type
expect_error(check_class(var = "character"))
expect_error(check_class(id, type = 12), class = "check_class_type_error")

# allowNULL
expect_error(check_class(id, type = "numeric", allowNULL = "x"), 
             class = "check_class_allowNULL_error")
expect_error(check_class(id, type = "numeric", allowNULL = NULL), 
             class = "check_class_allowNULL_error")
expect_error(check_class(id, type = "numeric", allowNULL = 12), 
             class = "check_class_allowNULL_error")

# individual error generated by function
expect_error(check_class(2, "character"), class = "rlang_error")
expect_error(check_class(2, "data.frame"), class = "rlang_error")
expect_error(check_class("2", "data.frame"), class = "rlang_error")
expect_error(check_class(NULL, "character", allowNULL = FALSE), class = "rlang_error")

id <- 1
err <- tryCatch(
  check_class(id, "character", allowNULL = FALSE),
  error = function(err) err
)
expect_true(inherits(err, c("rlang_error")))
expect_equal(err$value, 1)
expect_equal(err$current_class, "numeric")
